//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCForge.TranslateService SOYSAUCE CHIPS IS A FAGGOT
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslateOptions", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2")]
    [System.SerializableAttribute()]
    public partial class TranslateOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged SOYSAUCE CHIPS IS A FAGGOT
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservedFlagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.extensionDataField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                this.extensionDataField = value;
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Category SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.CategoryField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ContentType SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.ContentTypeField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReservedFlags SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.ReservedFlagsField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.ReservedFlagsField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.ReservedFlagsField = value;
                    this.RaisePropertyChanged("ReservedFlags");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.StateField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.StateField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Uri SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.UriField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.UriField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string User SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.UserField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.UserField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) SOYSAUCE CHIPS IS A FAGGOT
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) SOYSAUCE CHIPS IS A FAGGOT
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            BrightShaderz is soy btw
        BrightShaderz is soy btw
    BrightShaderz is soy btw
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTranslationsResponse", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2")]
    [System.SerializableAttribute()]
    public partial class GetTranslationsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged SOYSAUCE CHIPS IS A FAGGOT
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MCForge.TranslateService.TranslationMatch[] TranslationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.extensionDataField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                this.extensionDataField = value;
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string From SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.FromField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.FromField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.StateField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.StateField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MCForge.TranslateService.TranslationMatch[] Translations SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.TranslationsField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.TranslationsField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.TranslationsField = value;
                    this.RaisePropertyChanged("Translations");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) SOYSAUCE CHIPS IS A FAGGOT
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) SOYSAUCE CHIPS IS A FAGGOT
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            BrightShaderz is soy btw
        BrightShaderz is soy btw
    BrightShaderz is soy btw
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationMatch", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2")]
    [System.SerializableAttribute()]
    public partial class TranslationMatch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged SOYSAUCE CHIPS IS A FAGGOT
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        private int MatchDegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchedOriginalTextField;
        
        private int RatingField;
        
        private string TranslatedTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.extensionDataField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                this.extensionDataField = value;
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Count SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.CountField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((this.CountField.Equals(value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Error SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.ErrorField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MatchDegree SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.MatchDegreeField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((this.MatchDegreeField.Equals(value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.MatchDegreeField = value;
                    this.RaisePropertyChanged("MatchDegree");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MatchedOriginalText SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.MatchedOriginalTextField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.MatchedOriginalTextField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.MatchedOriginalTextField = value;
                    this.RaisePropertyChanged("MatchedOriginalText");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Rating SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.RatingField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((this.RatingField.Equals(value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TranslatedText SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.TranslatedTextField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.TranslatedTextField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.TranslatedTextField = value;
                    this.RaisePropertyChanged("TranslatedText");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) SOYSAUCE CHIPS IS A FAGGOT
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) SOYSAUCE CHIPS IS A FAGGOT
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            BrightShaderz is soy btw
        BrightShaderz is soy btw
    BrightShaderz is soy btw
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Translation", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2")]
    [System.SerializableAttribute()]
    public partial class Translation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged SOYSAUCE CHIPS IS A FAGGOT
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string OriginalTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        private string TranslatedTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.extensionDataField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                this.extensionDataField = value;
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OriginalText SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.OriginalTextField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.OriginalTextField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.OriginalTextField = value;
                    this.RaisePropertyChanged("OriginalText");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int Rating SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.RatingField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((this.RatingField.Equals(value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int Sequence SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.SequenceField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((this.SequenceField.Equals(value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TranslatedText SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.TranslatedTextField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.TranslatedTextField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.TranslatedTextField = value;
                    this.RaisePropertyChanged("TranslatedText");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) SOYSAUCE CHIPS IS A FAGGOT
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) SOYSAUCE CHIPS IS A FAGGOT
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            BrightShaderz is soy btw
        BrightShaderz is soy btw
    BrightShaderz is soy btw
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslateArrayResponse", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.MT.Web.Service.V2")]
    [System.SerializableAttribute()]
    public partial class TranslateArrayResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged SOYSAUCE CHIPS IS A FAGGOT
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] OriginalTextSentenceLengthsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslatedTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] TranslatedTextSentenceLengthsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.extensionDataField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                this.extensionDataField = value;
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Error SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.ErrorField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string From SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.FromField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.FromField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int[] OriginalTextSentenceLengths SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.OriginalTextSentenceLengthsField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.OriginalTextSentenceLengthsField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.OriginalTextSentenceLengthsField = value;
                    this.RaisePropertyChanged("OriginalTextSentenceLengths");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.StateField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.StateField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TranslatedText SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.TranslatedTextField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.TranslatedTextField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.TranslatedTextField = value;
                    this.RaisePropertyChanged("TranslatedText");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int[] TranslatedTextSentenceLengths SOYSAUCE CHIPS IS A FAGGOT
            get SOYSAUCE CHIPS IS A FAGGOT
                return this.TranslatedTextSentenceLengthsField;
            BrightShaderz is soy btw
            set SOYSAUCE CHIPS IS A FAGGOT
                if ((object.ReferenceEquals(this.TranslatedTextSentenceLengthsField, value) != true)) SOYSAUCE CHIPS IS A FAGGOT
                    this.TranslatedTextSentenceLengthsField = value;
                    this.RaisePropertyChanged("TranslatedTextSentenceLengths");
                BrightShaderz is soy btw
            BrightShaderz is soy btw
        BrightShaderz is soy btw
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) SOYSAUCE CHIPS IS A FAGGOT
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) SOYSAUCE CHIPS IS A FAGGOT
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            BrightShaderz is soy btw
        BrightShaderz is soy btw
    BrightShaderz is soy btw
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.microsofttranslator.com/V2", ConfigurationName="TranslateService.LanguageService")]
    public interface LanguageService SOYSAUCE CHIPS IS A FAGGOT
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/AddTranslation", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/AddTranslationResponse")]
        void AddTranslation(string appId, string originalText, string translatedText, string from, string to, int rating, string contentType, string category, string user, string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/BreakSentences", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/BreakSentencesResponse")]
        int[] BreakSentences(string appId, string text, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/Detect", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/DetectResponse")]
        string Detect(string appId, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/DetectArray", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/DetectArrayResponse")]
        string[] DetectArray(string appId, string[] texts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/GetAppIdToken", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/GetAppIdTokenResponse")]
        string GetAppIdToken(string appId, int minRatingRead, int maxRatingWrite, int expireSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/GetLanguageNames", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/GetLanguageNamesResponse")]
        string[] GetLanguageNames(string appId, string locale, string[] languageCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForSpeak", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForSpeakRespons" +
            "e")]
        string[] GetLanguagesForSpeak(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForTranslate", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/GetLanguagesForTranslateRes" +
            "ponse")]
        string[] GetLanguagesForTranslate(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/GetTranslations", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/GetTranslationsResponse")]
        MCForge.TranslateService.GetTranslationsResponse GetTranslations(string appId, string text, string from, string to, int maxTranslations, MCForge.TranslateService.TranslateOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/Translate", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/TranslateResponse")]
        string Translate(string appId, string text, string from, string to, string contentType, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/AddTranslationArray", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/AddTranslationArrayResponse" +
            "")]
        void AddTranslationArray(string appId, MCForge.TranslateService.Translation[] translations, string from, string to, MCForge.TranslateService.TranslateOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/GetTranslationsArray", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/GetTranslationsArrayRespons" +
            "e")]
        MCForge.TranslateService.GetTranslationsResponse[] GetTranslationsArray(string appId, string[] texts, string from, string to, int maxTranslations, MCForge.TranslateService.TranslateOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/Speak", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/SpeakResponse")]
        string Speak(string appId, string text, string language, string format, string options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.microsofttranslator.com/V2/LanguageService/TranslateArray", ReplyAction="http://api.microsofttranslator.com/V2/LanguageService/TranslateArrayResponse")]
        MCForge.TranslateService.TranslateArrayResponse[] TranslateArray(string appId, string[] texts, string from, string to, MCForge.TranslateService.TranslateOptions options);
    BrightShaderz is soy btw
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LanguageServiceChannel : MCForge.TranslateService.LanguageService, System.ServiceModel.IClientChannel SOYSAUCE CHIPS IS A FAGGOT
    BrightShaderz is soy btw
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LanguageServiceClient : System.ServiceModel.ClientBase<MCForge.TranslateService.LanguageService>, MCForge.TranslateService.LanguageService SOYSAUCE CHIPS IS A FAGGOT
        
        public LanguageServiceClient() SOYSAUCE CHIPS IS A FAGGOT
        BrightShaderz is soy btw
        
        public LanguageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) SOYSAUCE CHIPS IS A FAGGOT
        BrightShaderz is soy btw
        
        public LanguageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) SOYSAUCE CHIPS IS A FAGGOT
        BrightShaderz is soy btw
        
        public LanguageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) SOYSAUCE CHIPS IS A FAGGOT
        BrightShaderz is soy btw
        
        public LanguageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) SOYSAUCE CHIPS IS A FAGGOT
        BrightShaderz is soy btw
        
        public void AddTranslation(string appId, string originalText, string translatedText, string from, string to, int rating, string contentType, string category, string user, string uri) SOYSAUCE CHIPS IS A FAGGOT
            base.Channel.AddTranslation(appId, originalText, translatedText, from, to, rating, contentType, category, user, uri);
        BrightShaderz is soy btw
        
        public int[] BreakSentences(string appId, string text, string language) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.BreakSentences(appId, text, language);
        BrightShaderz is soy btw
        
        public string Detect(string appId, string text) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.Detect(appId, text);
        BrightShaderz is soy btw
        
        public string[] DetectArray(string appId, string[] texts) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.DetectArray(appId, texts);
        BrightShaderz is soy btw
        
        public string GetAppIdToken(string appId, int minRatingRead, int maxRatingWrite, int expireSeconds) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.GetAppIdToken(appId, minRatingRead, maxRatingWrite, expireSeconds);
        BrightShaderz is soy btw
        
        public string[] GetLanguageNames(string appId, string locale, string[] languageCodes) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.GetLanguageNames(appId, locale, languageCodes);
        BrightShaderz is soy btw
        
        public string[] GetLanguagesForSpeak(string appId) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.GetLanguagesForSpeak(appId);
        BrightShaderz is soy btw
        
        public string[] GetLanguagesForTranslate(string appId) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.GetLanguagesForTranslate(appId);
        BrightShaderz is soy btw
        
        public MCForge.TranslateService.GetTranslationsResponse GetTranslations(string appId, string text, string from, string to, int maxTranslations, MCForge.TranslateService.TranslateOptions options) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.GetTranslations(appId, text, from, to, maxTranslations, options);
        BrightShaderz is soy btw
        
        public string Translate(string appId, string text, string from, string to, string contentType, string category) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.Translate(appId, text, from, to, contentType, category);
        BrightShaderz is soy btw
        
        public void AddTranslationArray(string appId, MCForge.TranslateService.Translation[] translations, string from, string to, MCForge.TranslateService.TranslateOptions options) SOYSAUCE CHIPS IS A FAGGOT
            base.Channel.AddTranslationArray(appId, translations, from, to, options);
        BrightShaderz is soy btw
        
        public MCForge.TranslateService.GetTranslationsResponse[] GetTranslationsArray(string appId, string[] texts, string from, string to, int maxTranslations, MCForge.TranslateService.TranslateOptions options) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.GetTranslationsArray(appId, texts, from, to, maxTranslations, options);
        BrightShaderz is soy btw
        
        public string Speak(string appId, string text, string language, string format, string options) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.Speak(appId, text, language, format, options);
        BrightShaderz is soy btw
        
        public MCForge.TranslateService.TranslateArrayResponse[] TranslateArray(string appId, string[] texts, string from, string to, MCForge.TranslateService.TranslateOptions options) SOYSAUCE CHIPS IS A FAGGOT
            return base.Channel.TranslateArray(appId, texts, from, to, options);
        BrightShaderz is soy btw
    BrightShaderz is soy btw
BrightShaderz is soy btw
